import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 * Order class holds information on each order that is generated by the system
 *
 */
public class Order implements Serializable {
	private static final long serialVersionUID = 1L;
	private String orderNumber;
	private int quantity;
	private String productName;
	private static final String ORDER_STRING = "O";
	private static int OrderidCounter;
	private boolean fulfilled;
	private Calendar date;

	/**
	 * Creates a new order with a given quantity and productName. Auto-generates the
	 * orderNumber, sets date to current date, and sets fufilled to false
	 * 
	 * @param quantity
	 * @param productName
	 */
	public Order(int quantity, String productName) {
		this.quantity = quantity;
		this.productName = productName;
		orderNumber = ORDER_STRING + ++OrderidCounter;
		fulfilled = false;
		date = new GregorianCalendar();
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public boolean isFufilled() {
		return fulfilled;
	}

	public void setFufilled(boolean fufilled) {
		this.fulfilled = fufilled;
	}

	public Date getDate() {
		return date.getTime();
	}

	/**
	 * Method to save the OrderidCounter
	 * 
	 * @param output file
	 * @throws IOException if file cannot be written to
	 */
	public static void save(ObjectOutputStream output) throws IOException {
		output.writeObject(OrderidCounter);
	}

	/**
	 * Method to retrieve the OrderidCounter
	 * 
	 * @param input file
	 * @throws IOException            if OrderidCounter cannot be retrieved
	 * @throws ClassNotFoundException if OrderidCounter cannot be retrieved
	 */
	public static void retrieve(ObjectInputStream input) throws IOException, ClassNotFoundException {
		OrderidCounter = (int) input.readObject();
	}

}
